Repository tryber/sd-010-b-project-recipes-app, pull requests merged in 2021-07, with the labels that each got.

#106 [Grupo 13] - [Barra de Busca]
  README.md
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/components/DrinkCard.jsx
  src/components/FoodCard.jsx
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/css/SearchBar.css
  src/pages/Drinks.js
  src/pages/Explore.js
  src/pages/ExploreByArea.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreDrinksIngredients.js
  src/pages/ExploreFoods.js
  src/pages/ExploreFoodsIngredients.js
  src/pages/Foods.js
  src/pages/Perfil.js
  src/pages/bebidas.js
  src/pages/comidas.js
  src/reducers/drinkReducer.js
  src/reducers/foodReducer.js
  src/reducers/index.js
Labels: development

#70 Main-group-23 header
  package-lock.json
  src/App.css
  src/App.js
  src/components/Drinks.js
  src/components/Food.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.js
  src/components/Header/header.css
  src/helpers/localStoge.js
  src/helpers/requests.js
  src/pages/DrinkIngredients/DrinkIngredients.js
  src/pages/Drinks/Drinks.js
  src/pages/Explorar/Explorar.js
  src/pages/ExplorarBebidas/ExplorarBebidas.js
  src/pages/ExplorarComidas/ExplorarComidas.js
  src/pages/Food/Food.css
  src/pages/Food/Food.js
  src/pages/FoodIngredients/FoodIngredients.js
  src/pages/Login/Login.css
  src/pages/Login/Login.js
Labels: code-review

#201 [Group 19] [Tela Principal]
  src/App.js
  src/common/components/CategoryButton.jsx
  src/common/components/RecipeCard.jsx
  src/common/components/RecipeDetails.jsx
  src/common/pages/Login.jsx
  src/common/pages/Recipes.jsx
  src/context/Provider.js
  src/context/reducers/recipes.js
  src/context/reducers/user.js
  src/context/store.js
  src/fonts/PoetsenOne.ttf
  src/index.css
  src/services/index.js
Labels: code-review

#109 [Group 25] Tela de Login
  package-lock.json
  src/App.js
  src/index.js
  src/pages/Food.jsx
  src/pages/Login.jsx
Labels: code-review

#195 [Main group 31] requisitos 13 ao 16
  src/App.css
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/pages/Beverages.js
  src/pages/Food.js
  src/redux/actions/actionTypes.js
  src/redux/actions/index.js
  src/redux/reducers/fetchApiReducer.jsx
  src/redux/reducers/index.js
  src/services/fetchApi.jsx
Labels: code-review

#173 [Group 26] Ingredientes
  src/App.js
  src/components/Footer.js
  src/components/Header.js
  src/components/SearchForm.js
  src/components/SearchIcon.js
  src/components/style/Footer.css
  src/components/style/Header.css
  src/components/style/IngredientsMeal.css
  src/components/style/SearchForm.css
  src/context/RecipesProvider.js
  src/data/pathLocationNames.js
  src/pages/Explore.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreMeals.js
  src/pages/FoodList.js
  src/pages/IngredientDrink.js
  src/pages/IngredientMeals.js
  src/pages/Login.js
  src/pages/Recipes.js
  src/pages/style/Explore.css
  src/services/APIEndpoints.js
  src/services/AllowanceToRender.js
  src/services/IngredientsRacipesAPI.js
  src/services/RandomRacipeAPI.js
  src/services/RecipesAPI.js
  src/services/pageTitleByLocation.js
Labels: development

#151 Main group 28 barra de busca
  README.md
  src/components/CardsDeReceitas.jsx
  src/components/Footer.jsx
  src/components/FooterIcons/Drink.jsx
  src/components/FooterIcons/Explore.jsx
  src/components/FooterIcons/Meal.jsx
  src/components/Header.jsx
  src/components/SearchInput.jsx
  src/context/AppReceitasProvider.jsx
  src/css/footer.css
  src/pages/Bebidas.jsx
  src/pages/Comidas.jsx
  src/pages/Login.jsx
  src/services/servicesApi.js
Labels: development

#218 Group 20 - Search Bar integrando com Header e Tela Principal
  README.md
  package-lock.json
  package.json
  src/App.css
  src/components/Card.jsx
  src/components/FilteredList.jsx
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/components/Teste.jsx
  src/context/DrinksProvider.js
  src/context/RecipesProvider.js
  src/pages/Drinks.jsx
  src/pages/Login.jsx
  src/pages/Recipes.jsx
  src/routes/routes.jsx
  src/services/DrinksServices.js
  src/services/RecipesServices.js
  src/styles/Card.css
Labels: code-review

#190 [GRUPO 30] page: Recipe in progress req 47 - 53
  src/App.css
  src/App.jsx
  src/components/FavoriteBtn.jsx
  src/components/ShareBtn.jsx
  src/components/index.js
  src/context/AppRecipeContext.js
  src/context/AppRecipeProvider.jsx
  src/main.css
  src/pages/MainPage.jsx
  src/pages/RecipeInProgress.jsx
  src/pages/index.js
  src/reducers/index.js
  src/reducers/recipes.js
  src/services/index.js
  src/services/localStorageManager.js
Labels: development

#265 [Grupo 20] [Páginas de Explorar e Explorar Comidas/Bebidas]
  src/App.css
  src/components/Card.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/context/DrinksProvider.js
  src/context/RecipesProvider.js
  src/pages/DrinkDetail.jsx
  src/pages/Explore.jsx
  src/pages/ExploreDrinkIngredients.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreFoods.jsx
  src/pages/Profile.jsx
  src/services/DrinksServices.js
  src/services/RecipesServices.js
  src/styles/Card.css
  src/styles/Explore.css
  src/styles/ExploreDrinks.css
  src/styles/ExploreFoods.css
  src/styles/Footer.css
  src/styles/Profile.css
Labels: code-review

#266 requisitos 25 ao 32
  src/components/SearchBar.jsx
  src/pages/Beverages.js
  src/pages/Food.js
  src/services/fetchApi.jsx
Labels: code-review

#267 [Group 21][Requisito 77]
  src/App.css
  src/components/CardIngre.jsx
  src/context/drinksContext.jsx
  src/context/mealsContext.jsx
  src/hooks/useMealsAndDrinks.jsx
  src/pages/Recipes.jsx
Labels: bug

#227 Main-group-23 header requisito 10, 11, 12
  package-lock.json
  src/App.js
  src/components/Header/Header.js
  src/pages/Drinks/Drinks.js
  src/pages/Explore/Explore.js
  src/pages/ExploreDrinks/ExploreDrinks.js
  src/pages/ExploreFood/ExploreFood.js
  src/pages/ExploreFoodOrigin/ExploreFoodOrigin.js
  src/pages/Food/Food.js
  src/pages/Profile/Profile.js
  src/pages/RecipesFavorites/RecipesFavorites.js
  src/pages/RecipesMade/RecipesMade.js
Labels: code-review

#299 [GROUP 19] [Recipe in progress]
  src/App.js
  src/common/components/LikeButton.jsx
  src/common/components/RecipeCard.jsx
  src/common/components/RecipeDetails.jsx
  src/common/components/RecipeInProgress.jsx
  src/common/components/RenderRecipe.jsx
  src/common/components/ShareButton.jsx
  src/common/pages/DoneRecipes.jsx
  src/common/pages/Recipes.jsx
  src/context/reducers/recipes.js
  src/context/store.js
  src/functions/index.js
  src/index.css
  src/services/index.js
Labels: code-review

#297 [GRUPO 30] fix: Saves 'in progress recipes' properly in local storage
  src/services/localStorageManager.js
Labels: code-review

#246 [Group 1][Footer]
  src/components/Footer.js
  src/components/Header.js
  src/components/components.css
  src/components/header.css
  src/pages/Drinks/ExploreDrink.js
  src/pages/Drinks/ExploreIngredientsDrink.js
  src/pages/Drinks/MainDrinks.js
  src/pages/Explore.js
  src/pages/Foods/ExploreCountry.js
  src/pages/Foods/ExploreFood.js
  src/pages/Foods/ExploreIngredientsFood.js
  src/pages/Foods/MainFood.js
  src/pages/Profile.js
Labels: code-review

#160 [Group 6][Feat][Req 19 - 24]
  src/components/Menu.css
  src/components/Menu.js
  src/pages/Explore/Explore.js
  src/pages/Explore/ExploreArea.js
  src/pages/Explore/ExploreDrinksFood.js
  src/pages/Explore/ExploreIngredients.js
  src/pages/Recipes/RecipesPrincipal.js
Labels: code-review

#264 [Grupo 16] footer req 19 ao 24
  src/App.css
  src/components/Cards.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/context/FetchContext.js
  src/context/FetchProvider.js
  src/index.js
  src/pages/Drinks.jsx
  src/pages/Explorar.jsx
  src/pages/Foods.jsx
  src/pages/OrigensFoods.jsx
  src/pages/Perfil.jsx
  src/pages/SearchDrinks.jsx
  src/pages/SearchDrinksIngredients.jsx
  src/pages/SearchFoods.jsx
  src/pages/SearchFoodsIngredients.jsx
Labels: code-review

#141 [Group 5] Add req 09 ao 21
  src/Style/DownMenu.css
  src/Style/Header.css
  src/Style/Login.css
  src/actions/index.js
  src/components/DownMenu.jsx
  src/components/Header.jsx
  src/components/Search.jsx
  src/pages/Drinks.jsx
  src/pages/DrinksByIngredients.jsx
  src/pages/DrinksExplorer.jsx
  src/pages/Explorer.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/Login.jsx
  src/pages/Perfil.jsx
  src/pages/Recipes.jsx
  src/pages/RecipesByIngredients.jsx
  src/pages/RecipesByOrigin.jsx
  src/pages/RecipesDone.jsx
  src/pages/RecipesExplorer.jsx
  src/reducers/drink.js
  src/reducers/recipes.js
  src/reducers/user.js
  src/services/api.js
Labels: code-review

#221 Main group 7 tela principal
  src/components/Form.js
  src/components/List.js
  src/components/Search.js
  src/pages/DrinkDetails.js
  src/pages/DrinkRecipes.js
  src/pages/FoodDetails.js
  src/pages/FoodRecipes.js
  src/services/api.js
  src/services/searchApi.js
  src/styles/global.css
  yarn.lock
Labels: code-review

#287 [GRUPO 22] Req-14 and 25-26 refactored
  src/App.js
  src/components/Card.jsx
  src/components/Header.jsx
  src/components/MainCards.jsx
  src/components/SearchBar.jsx
  src/contexts/CocktailsContext.jsx
  src/contexts/CocktailsProvider.jsx
  src/contexts/MealsContext.jsx
  src/contexts/MealsProvider.jsx
  src/contexts/RecipesContext.jsx
  src/contexts/RecipesProvider.jsx
  src/helpers/CocktailsAPI.js
  src/helpers/MealsAPI.js
  src/helpers/api.js
  src/index.js
  src/pages/Bebidas.jsx
  src/pages/Comidas.jsx
  src/pages/MainPage.jsx
Labels: code-review

#257 [Group 26] area
  src/App.js
  src/context/RecipesProvider.js
  src/pages/ExploreArea.js
  src/pages/ExploreDrinks.js
  src/pages/IngredientDrink.js
  src/pages/NotFound.js
  src/pages/style/ExploreArea.css
  src/pages/style/ExploreDrinks.css
  src/services/APIEndpoints.js
  src/services/RecipesAPI.js
Labels: development

#304 [Group 6] Requisito 10
  src/components/Header.js
  src/context/Provider.jsx
  src/pages/Explore/Explore.js
  src/pages/Explore/ExploreArea.js
  src/pages/Explore/ExploreDrinksFood.js
  src/pages/Explore/ExploreIngredients.js
  src/pages/Recipes/RecipesDone.js
  src/pages/Recipes/RecipesFavorites.js
  src/pages/Recipes/RecipesPrincipal.js
  src/pages/User/Login.js
  src/pages/User/Perfil.js
Labels: bug, code-review

#333 [Grupo 20] [Tela Explorar Ingredientes - Comidas/Bebidas]
  src/components/IngredientCard.jsx
  src/context/DrinksProvider.js
  src/context/RecipesProvider.js
  src/pages/Explore.jsx
  src/pages/ExploreDrinkIngredients.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreFoodIngredients.jsx
  src/pages/ExploreFoods.jsx
  src/services/DrinksServices.js
  src/services/RecipesServices.js
  src/styles/Card.css
  src/styles/Footer.css
  src/styles/IngredientCard.css
Labels: code-review

#21 [GRUPO 30] Criando header de busca.
  .gitignore
  src/App.jsx
  src/actions/getRecipes.js
  src/actions/saveCardsContent.js
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/components/index.js
  src/pages/MainPage.jsx
  src/pages/Profile.jsx
  src/pages/index.js
  src/reducers/cardsContent.js
  src/reducers/index.js
  src/reducers/saveRecipes.js
  src/services/index.js
Labels: development

#347 [Main group 24] feito merge e resolvido conflitos
  src/App.js
  src/Pages/Detalhes.jsx
  src/Pages/Explorar/ExpBebidas.jsx
  src/Pages/Explorar/ExpComidas.jsx
  src/Pages/Explorar/Explorar.jsx
  src/Pages/ReceitaEmProcesso.jsx
  src/components/CocktailList.jsx
  src/components/Header.jsx
  src/components/MealList.jsx
  src/components/SearchBar.jsx
Labels: code-review

#270 [Main-Group-6][Req-18]
  src/components/BtnDrinks.js
  src/components/BtnFoods.js
  src/components/Search.js
  src/context/Provider.jsx
Labels: bug

#346 Group 20 done-recipes
  src/pages/FinishedRecipes.jsx
  src/pages/Profile.jsx
  src/styles/DoneRecipes.css
Labels: code-review

#193 [Grupo 15] Requisito 27: Parcial 50% (Não encontra os botoes na tela de bebidas)
  cypress/integration/footer_spec.js
  cypress/integration/recipes_list_spec.js
  src/App.css
  src/App.test.js
  src/api/fetchCategories.js
  src/components/FilterBar.js
  src/context/RecipesProvider.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/Explorar.js
Labels: code-review

#357 Fix: Resolving requirement 16 - [DONE]
  src/App.js
  src/components/BtnDrinks.js
  src/components/BtnFoods.js
  src/context/Provider.jsx
Labels: code-review

#348 [Grupo 6][Feat][Reqs-67-68-69]
  src/pages/Explore/Explore.js
  src/pages/User/Login.js
  src/pages/User/Perfil.js
Labels: code-review

#375 [Main group 24] Resolvido Conflitos das páginas de Explorar!
  src/App.js
  src/Pages/Explorar/ExpBebidas.jsx
  src/Pages/Explorar/ExpComidas.jsx
  src/Pages/Explorar/Explorar.jsx
Labels: code-review

#390 [Grupo 20] [Página Explorar Local de Origem]
  src/components/IngredientCard.jsx
  src/pages/ExploreFoodsArea.jsx
  src/pages/FinishedRecipes.jsx
  src/pages/NotFound.jsx
  src/routes/routes.jsx
  src/services/RecipesServices.js
  src/styles/ExploreFoodArea.css
  src/styles/IngredientCard.css
Labels: code-review

#399 Group20 favorites page
  src/components/Favorited.jsx
  src/pages/FavoritesRecipes.jsx
Labels: code-review

#292 [Grupo 20][Requisitos 33 a 46]
  package-lock.json
  package.json
  src/components/ButtonStartRecipe.jsx
  src/components/HeaderDetails.jsx
  src/components/IngredientsDetails.jsx
  src/components/InstructionsDetails.jsx
  src/components/Recommended.jsx
  src/context/DrinksProvider.js
  src/context/LoginProvider.js
  src/context/RecipesProvider.js
  src/pages/DrinkDetail.jsx
  src/pages/FoodDetail.jsx
  src/pages/Login.jsx
  src/services/DrinksServices.js
  src/services/RecipesServices.js
  src/styles/HeaderDetails.css
  src/styles/Recommended.css
Labels: code-review

#355 G9 Tela de Detalhes
  package-lock.json
  package.json
  src/App.js
  src/components/CardsCarousel.css
  src/components/CardsCarousel.js
  src/components/DetailsImage.js
  src/components/EmbedVideo.js
  src/components/Ingredients.js
  src/components/Instructions.js
  src/components/Title.js
  src/pages/DetailsButton.js
  src/pages/ReceitaDetalhes.css
  src/pages/ReceitaDetalhes.js
  src/pages/ReceitaEmProgresso.js
  src/services/CheckFavorites.js
  src/services/CheckInProgress.js
  src/services/RecipeDetailsFetch.js
  src/services/SaveWithFavorites.js
Labels: code-review

#368 [Main Group 6] Requisito 12
  src/components/HeaderWithButton.js
  src/pages/Recipes/RecipesPrincipal.js
  src/pages/User/Perfil.js
Labels: code-review

#364 Main group 28 tela receitas
  src/App.js
  src/components/CardsDeReceitas.jsx
  src/components/ListaCategoriasReceitas.jsx
  src/pages/DetailsReceita.jsx
  src/pages/Receitas.jsx
Labels: code-review

#420 G9 receita em progresso
  .a
  src/App.js
  src/pages/Ingredientes.jsx
Labels: code-review

#351 [Group 26] done recipes
  src/App.js
  src/pages/DoneRecipes.js
  src/pages/Profile.js
  src/pages/style/DoneRecipes.css
  src/services/endpoints.js
  src/services/recipesAPI.js
Labels: development

#426 [Main-Group 6] [Req25-26]
  README.md
  src/components/BtnDrinks.js
  src/components/BtnFoods.js
  src/context/Provider.jsx
  src/pages/Recipes/RecipesPrincipal.js
Labels: code-review

#379 [Group 5] Tela Search Bar
  cypress/mocks/fetch.js
  src/actions/index.js
  src/actions/types.js
  src/components/Header.jsx
  src/components/Search.jsx
  src/pages/Drinks.jsx
  src/pages/Perfil.jsx
  src/pages/Recipes.jsx
  src/pages/Routers.js
  src/reducers/drink.js
  src/reducers/recipes.js
  src/services/api.js
Labels: development

#434 [Group 6] Req 70, 71, 72 e 73
  src/components/BtnExpDrink.js
  src/components/BtnExpFood.js
  src/pages/Explore/ExploreDrinksFood.js
Labels: code-review

#398 [Group 19] [Recipe Details]
  package-lock.json
  package.json
  src/App.js
  src/common/components/RecipeCard.jsx
  src/common/components/RecipeDetails.jsx
  src/common/components/RecipeIngredients.jsx
  src/common/components/RecommendedRecipes.jsx
  src/common/components/RenderDetails.jsx
  src/common/components/RenderRecipe.jsx
  src/common/pages/Cocktails.jsx
  src/common/pages/RecipeDetails.jsx
  src/common/pages/RecipeInProgress.jsx
  src/context/reducers/recipes.js
  src/context/store.js
  src/functions/index.js
  src/index.css
Labels: code-review

#447 [Main-group-6][Req-27]
  src/context/Provider.jsx
  src/pages/Recipes/RecipesPrincipal.js
Labels: code-review

#410 [Grupo 15] Requisito 29
  cypress/integration/recipes_list_spec.js
  src/api/fetchCategories.js
  src/components/FilterBar.js
  src/context/RecipesProvider.js
Labels: development

#474 [Group 1] [ Explorar] - Concluída
  src/App.css
  src/Redux/actions/index.js
  src/Redux/reducers/recipeList.js
  src/components/FilterRecipe.js
  src/components/RecipeList.js
  src/components/SearchFood.js
  src/index.css
  src/pages/Drinks/MainDrinks.js
  src/pages/Explore.js
  src/pages/Foods/MainFood.js
  src/pages/Profile.js
  src/pages/RecipeDone.js
  src/services/recipeAPI.js
Labels: code-review

#432 [Group 26] favorite recipes
  src/App.js
  src/pages/FavoriteRecipes.js
  src/pages/style/FavoriteRecipes.css
Labels: development

#435 [Grupo 28] - Tela de Perfil
  src/pages/Perfil.jsx
  src/services/localStorage.js
Labels: code-review

#471 [Grupo 20] [Testes/1]
  src/components/Footer.jsx
  src/components/Header.jsx
  src/pages/FoodDetail.jsx
  src/pages/Profile.jsx
  src/renderWithRouter.js
  src/tests/Explore.test.js
  src/tests/ExploreDrinks.test.js
  src/tests/ExploreFoods.test.js
  src/tests/Footer.test.js
  src/tests/Login.test.js
  src/tests/NotFound.test.js
  src/tests/Perfil.test.js
Labels: code-review

#464 Main group 30 requi33 46
  package-lock.json
  package.json
  src/App.jsx
  src/components/FavoriteBtn.jsx
  src/components/IngList.jsx
  src/components/MealClip.jsx
  src/components/RecDrinks.css
  src/components/RecDrinks.jsx
  src/components/RecImages.jsx
  src/components/RecMeals.jsx
  src/components/index.js
  src/pages/FoodDetails.css
  src/pages/FoodDetails.jsx
  src/pages/Login.jsx
  src/pages/index.js
  src/services/localStorageManager.js
  src/tests/Login.test.jsx
  src/tests/renderWithRouter.js
Labels: code-review

#388 Main-group-23 style
  src/App.js
  src/app.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/header.css
  src/pages/Drinks/Drinks.css
  src/pages/Drinks/Drinks.js
  src/pages/Food/Food.css
  src/pages/Food/Food.js
Labels: code-review

#490 [Grupitcho 24] Tela principal de Receitar (Reqs 27 a 32)
  src/Pages/Bebidas.jsx
  src/Pages/Comidas.jsx
  src/apis/CocktailsApis.js
  src/apis/MealsApis.js
  src/components/CategoryButton.jsx
  src/components/CategoryFilter.jsx
  src/components/CocktailList.jsx
  src/components/Header.jsx
  src/components/MealList.jsx
  src/context/Provider.js
  src/styles/categories.css
Labels: code-review

#468 [Main Group 27][Explore Pages]
  src/App.js
  src/Service/drinkApi.js
  src/Service/foodApi.js
  src/components/CardIngredient.jsx
  src/components/FavoriteButton.jsx
  src/pages/Explorar.jsx
  src/pages/Explore.jsx
Labels: code-review

#494 [Group 6] Requisito 74
  src/components/BtnExpDrink.js
  src/components/BtnExpFood.js
Labels: code-review

#510 [Main-Group-6][Req-17][Bug]
  src/components/BtnDrinks.js
  src/components/BtnFoods.js
  src/components/Search.js
  src/context/Provider.jsx
  src/pages/Recipes/RecipesPrincipal.js
Labels: bug

#508 [Main-group-6][Reqs-54-59]
  package-lock.json
  package.json
  src/components/CSS/doneRecipesCard.css
  src/components/DoneRecipesCard.js
  src/context/Provider.jsx
  src/pages/Recipes/RecipesDone.js
  src/pages/User/Login.js
Labels: code-review

#512 css feito
  src/components/Card.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/images/notfound.png
  src/pages/Drinks.jsx
  src/pages/Login.jsx
  src/pages/NotFound.jsx
  src/pages/Profile.jsx
  src/pages/Recipes.jsx
  src/routes/routes.jsx
  src/styles/Card.css
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/Login.css
  src/styles/NotFound.css
  src/styles/Profile.css
Labels: code-review

#511 [Main-Group-6][Req-17][2-Bug]
  src/context/Provider.jsx
  src/pages/Recipes/RecipesPrincipal.js
Labels: bug

#507 Main group 4 details Recipes
  src/App.js
  src/components/DetailsRecipes.jsx
  src/components/Header.jsx
  src/components/HeaderRecipes.jsx
  src/components/Ingredients.jsx
  src/components/Instructions.jsx
  src/components/SearchBar.jsx
  src/components/index.js
  src/context/DrinksProvider.js
  src/context/MealsProvider.js
  src/index.js
  src/pages/Drinks.jsx
  src/pages/DrinksDetails.jsx
  src/pages/Meals.jsx
  src/pages/MealsByArea.jsx
  src/pages/MealsDetails.jsx
  src/pages/RecipeInProgress.jsx
  src/pages/index.js
  src/services/api/RecipesApi.js
  src/services/api/RecomendationApi.js
  src/services/api/fetchById.jsx
  src/styles/RecipesDetails.css
Labels: code-review

#516 [Main-Group-6][Req-28]
  src/context/Provider.jsx
  src/pages/Recipes/RecipesPrincipal.js
Labels: code-review

#518 [Grupo 20] [CSS Telas de Explorar]
  src/components/FilteredList.jsx
  src/components/IngredientCard.jsx
  src/components/SearchBar.jsx
  src/pages/Explore.jsx
  src/pages/ExploreDrinkIngredients.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreFoodIngredients.jsx
  src/pages/ExploreFoods.jsx
  src/pages/NotFound.jsx
  src/styles/Explore.css
  src/styles/ExploreDrinks.css
  src/styles/ExploreFoods.css
  src/styles/ExploreRecipesIngredients.css
  src/styles/IngredientCard.css
  src/tests/Card.test.js
Labels: code-review

#536 [GRUPO 19][Recipe Details | Recipe In Progress][Refactory]
  src/common/components/Footer/Footer.jsx
  src/common/components/LikeButton.jsx
  src/common/components/RecipeIngredients.jsx
  src/common/components/RenderDetails.jsx
  src/common/components/ShareButton.jsx
  src/common/pages/RecipeDetails.jsx
  src/common/pages/RecipeInProgress.jsx
  src/common/pages/Recipes.jsx
  src/context/reducers/recipes.js
  src/context/store.js
  src/functions/index.js
  src/index.css
Labels: code-review

#495 [Grupo 16] req 67 ao 74
  src/pages/Explorar.jsx
  src/pages/SearchDrinks.jsx
  src/pages/SearchFoods.jsx
  src/services/Api.js
Labels: code-review

#489 [Group 5] Add Categorias Recipes Drinks
  src/Style/Recipes.css
  src/actions/index.js
  src/components/ButtonCategories.jsx
  src/components/CardItem.jsx
  src/pages/Drinks.jsx
  src/pages/Perfil.jsx
  src/pages/Recipes.jsx
  src/reducers/categories.js
  src/reducers/drink.js
  src/reducers/index.js
  src/reducers/recipes.js
  src/services/api.js
Labels: code-review

#466 [Grupo 15] Requisito 31
  src/components/FilterBar.js
  src/context/RecipesProvider.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/service/FoodDrinksRequest.js
Labels: development

#284 [GRUPO 30] page: Favorite Recipes
  src/App.jsx
  src/components/FavoriteBtn.jsx
  src/components/ShareBtn.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/RecipeInProgress.jsx
  src/pages/index.js
Labels: code-review

#523 [Main group 27 ][Details Recipe]
  cypress/integration/recipe_detail_spec.js
  src/components/CategoryDrinks.jsx
  src/components/DrinksDetails.jsx
  src/components/FavoriteButton.jsx
  src/components/MealsDetails.jsx
Labels: code-review

#306 [GROUP 19] [Req-DoneRecipes]
  package-lock.json
  src/common/components/CategoryButton.jsx
  src/common/components/DoneRecipeCard.jsx
  src/common/components/Footer/Footer.jsx
  src/common/components/ShareButton.jsx
  src/common/pages/DoneRecipes.jsx
  src/common/pages/comidas.js
  src/index.css
Labels: code-review

#553 Main group 28 tela receitas feitas
  src/App.js
  src/pages/ReceitasFeitas.jsx
Labels: development

#515 Implementa a logica de filtrar as refeiçoes por area
  src/App.js
  src/pages/FoodByCountry.js
  src/pages/FoodDetails.js
  src/pages/NotFound.js
  src/services/api.js
Labels: development

#564 [GRUPO 30] task: Add Header on the required pages
  src/components/Header.jsx
  src/pages/DoneRecipes.jsx
  src/pages/Explore.jsx
  src/pages/ExploreArea.jsx
  src/pages/ExploreIngredients.jsx
  src/pages/ExploreMealsOrDrinks.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/Profile.jsx
  src/services/getPageTitle.js
Labels: code-review

#571 Main group 28 tela receitas feitas v2.0
  src/pages/ReceitasFeitas.jsx
Labels: code-review

#565 [Group 19][Profile Page]
  src/App.js
  src/common/components/LikeButton.jsx
  src/common/pages/FavoriteRecipes.jsx
  src/common/pages/Profile.jsx
  src/common/pages/comidas.js
  src/index.css
Labels: code-review

#576 [Grupo 15] Requisitos 67 até 74
  cypress/integration/explore_by_ingredient_spec.js
  src/pages/Explorar.js
  src/pages/ExplorarBebidas.js
  src/pages/ExplorarComidas.js
Labels: code-review

#423 [Group 20] Style Pages Details
  package-lock.json
  package.json
  src/components/ButtonStartRecipe.jsx
  src/components/HeaderDetails.jsx
  src/components/IngredientsDetails.jsx
  src/components/InstructionsDetails.jsx
  src/components/Recommended.jsx
  src/context/LoginProvider.js
  src/pages/DrinkDetail.jsx
  src/pages/DrinkProgress.jsx
  src/pages/FoodDetail.jsx
  src/pages/FoodProgress.jsx
  src/styles/Details.js
  src/styles/HeaderDetails.css
  src/styles/InProgress.js
  src/styles/Recommended.css
  src/styles/checked.css
  src/styles/reset.css
  yarn.lock
Labels: code-review

#581 [Group 5] ADD req 33 ao 47
  package-lock.json
  package.json
  src/Style/RecipeDetails.css
  src/components/Ingredients.jsx
  src/pages/DrinkDetails.jsx
  src/pages/RecipeDetails.jsx
Labels: code-review

#566 Main group 3 - req74
  src/App.js
  src/pages/ExploreMealsOrDrinks.js
  src/pages/FoodAndDrinkById.js
  src/services/apiRequest.js
Labels: code-review

#554 [Main-Group-6][Req-34]
  src/App.js
  src/context/Provider.jsx
  src/pages/Recipes/RecipesDetails.js
Labels: code-review

#593 [Main-Group-6][Req-33]
  src/context/Provider.jsx
  src/pages/Recipes/RecipesDetails.js
Labels: code-review

#599 [Grup 18] CSS receitas feitas e receitas favoritas
  package-lock.json
  src/components/DoneRecipesCard.jsx
  src/components/FavoritesRecipesCard.jsx
  src/pages/DoneRecipes.jsx
  src/pages/FavoritesRecipes.jsx
  src/styles/doneRecipes.css
  src/styles/favoriteRecipes.css
Labels: code-review

#577 [GRUPO 20] [ESTILIZAÇÃO - CSS]
  package-lock.json
  src/index.css
  src/pages/ExploreFoodsArea.jsx
  src/styles/Explore.css
  src/styles/ExploreFoodArea.css
  src/tests/Card.test.js
  src/tests/Perfil.test.js
  yarn.lock
Labels: code-review

#590 [Grupo 30] task: Get finished recipes from local storage instead redux global state | req 54 - 59
  src/actions/index.js
  src/components/DoneCard.jsx
  src/pages/Login.jsx
  src/pages/RecipeInProgress.jsx
  src/reducers/done.js
  src/services/localStorageManager.js
Labels: code-review

#606 [Grupitcho 24] - Explorar Ingredientes (Reqs 75, 76 e 77)
  src/Pages/Bebidas.jsx
  src/Pages/Explorar/ExpBebidasIngredientes.jsx
  src/Pages/Explorar/ExpComidasIngredientes.jsx
  src/apis/CocktailsApis.js
  src/apis/MealsApis.js
  src/components/CategoryButton.jsx
  src/components/CocktailList.jsx
  src/components/IngredientCard.jsx
  src/components/IngredientList.jsx
  src/components/MealList.jsx
  src/context/Provider.js
Labels: code-review

#610 Main group 24 - Styling
  src/Pages/Explorar/ExpBebidas.jsx
  src/Pages/Explorar/ExpComidas.jsx
  src/Pages/Explorar/Explorar.jsx
  src/Pages/Login.jsx
  src/components/CocktailList.jsx
  src/components/Header.jsx
  src/components/IngredientCard.jsx
  src/components/IngredientList.jsx
  src/components/ItemCard.jsx
  src/components/MealList.jsx
  src/styles/footerCss.css
  src/styles/header.css
  src/styles/item-card.css
Labels: code-review

#613 [GRUPO 30] - fix req 10
  src/components/DoneCard.jsx
Labels: code-review

#433 G9 Receita em Progresso - Corrigido
  .a
  package-lock.json
  package.json
  src/App.js
  src/components/DetailsButton.js
  src/components/InProgressButton.js
  src/components/Ingredients.js
  src/components/IngredientsStep-bckup.js
  src/components/IngredientsStep.js
  src/pages/DetailsButton.js
  src/pages/ReceitaDetalhes.js
  src/pages/ReceitaEmProgresso.js
  src/services/CheckInProgress.js
  src/services/CheckboxesChecked.js
  src/services/GetIngredients.js
  src/services/LoadInProgress.js
  src/services/SaveInProgress.js
  src/services/SaveToFavorites.js
  src/services/SaveWithFavorites.js
  src/styles/ReceitaDetalhes.css
Labels: code-review

#615 [Grupo 30] task: Fix footer on the buttom - req 20 - 21
  src/components/Footer.jsx
  src/components/footer.css
  src/pages/Profile.jsx
Labels: code-review

#602 [Group 25] [receitas favoritas]
  src/components/DrinkPrepProgress.jsx
  src/components/FoodPrepProgress.jsx
  src/components/FoodPreparation.jsx
  src/components/Header.jsx
  src/pages/DrinkInProgress.jsx
  src/pages/FavoritesRecipes.jsx
  src/pages/FoodDetails.jsx
  src/pages/FoodInProgress.jsx
  src/pages/Login.jsx
Labels: code-review

#429 Main group 28 details receita
  src/App.css
  src/App.js
  src/components/CardsDeReceitas.jsx
  src/pages/DetailsReceita.jsx
  src/pages/Login.jsx
  src/pages/ReceitaEmProgresso.jsx
  src/pages/Receitas.jsx
  src/pages/detailsElements/CarouselElement.jsx
  src/pages/detailsElements/IngredientsList.jsx
  src/pages/detailsElements/Titulo.jsx
  src/services/localStorage.js
  src/services/servicesApi.js
Labels: code-review

#619 [GRUPO 28]Button Compartilhar completo
  src/components/ButtonCompartilhar.jsx
  src/pages/ReceitasFeitas.jsx
Labels: code-review

#631 Main-group-23 initial commit correções
  src/pages/ExplorerDrinks/ExplorerDrinks.js
  src/pages/ExplorerFoods/ExplorerFoods.js
Labels: code-review

#634 [Grupo 30] fix: req 32
  src/components/DoneCard.jsx
  src/components/FavoriteBtn.jsx
  src/components/IngList.jsx
  src/components/RecMeals.jsx
  src/components/RecipeCards.jsx
  src/pages/ExploreArea.jsx
  src/pages/ExploreMealsOrDrinks.jsx
  src/services/index.js
  src/services/localStorageManager.js
Labels: code-review

#626 [Main Group 31] [Requisitos 60 66]
  src/pages/BeveragesInProgress.js
  src/pages/DoneRecipes.js
  src/pages/FavoriteRecipes.js
  src/pages/FoodInProgress.js
Labels: code-review

#493 [Main group 5] Explore pages
  README.md
  package-lock.json
  package.json
  src/actions/index.js
  src/pages/DrinksExplorer.jsx
  src/pages/Explorer.jsx
  src/pages/Recipes.jsx
  src/pages/RecipesByIngredients.jsx
  src/pages/RecipesExplorer.jsx
  src/services/api.js
Labels: code-review

#366 [MAIN-GROUP-31] Requisitos 47 a 53
  cypress/integration/recipe_in_progress_spec.js
  package-lock.json
  src/App.js
  src/components/BeveragesInProgressInfo.jsx
  src/components/FoodInProgressInfo.jsx
  src/pages/BeverageRecipe.js
  src/pages/BeveragesInProgress.js
  src/pages/FoodInProgress.js
  src/pages/FoodRecipe.js
  src/resources/functions_drinks.js
Labels: code-review

#642 G9-Estilos
  src/App.css
  src/components/CardsCarousel.js
  src/components/DetailsButton.js
  src/components/EmbedVideo.js
  src/components/Footer.js
  src/images/logo.svg
  src/pages/Login.js
  src/styles/CardsCarousel.css
  src/styles/Explorar.css
  src/styles/Footer.css
  src/styles/Login.css
  src/styles/ReceitaDetalhes.css
  src/styles/card.css
  src/styles/header.css
Labels: code-review

#617 Main group 25 searchbar
  package-lock.json
  src/ContextApi/Provider.js
  src/RequisiçõesAPI/searchBar/RequestSearchBar.js
  src/components/FoodPreparation.jsx
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/pages/Drink.jsx
  src/pages/FavoritesRecipes.jsx
  src/pages/Food.jsx
Labels: code-review

#621 [Main-Group-6][Req-35]
  src/pages/Recipes/RecipesDetails.js
Labels: code-review

#653 [Main-Group-6][Fix: requirement 64 [DONE]]
  src/components/FavoriteRecipesCard.js
Labels: code-review

#654 Main group 6 req 30
  src/pages/Recipes/RecipesPrincipal.js
Labels: bug

#655 [Main-Group-6][Req-43]
  src/pages/Recipes/RecipesDetails.js
Labels: code-review

#656 [Main-Group-6][Req-37]
  src/pages/Recipes/RecipesDetails.js
  src/pages/Recipes/RecipesPrincipal.js
  src/styles/RecipesDetails.css
Labels: code-review

#657 [Main-Group-6][Reqs-75-76]
  src/pages/Explore/ExploreIngredients.js
Labels: code-review

#659 [Main-Group-6]Req-47]
  src/pages/Recipes/RecipesProgress.js
Labels: code-review

#652 [Group 1] [Tela Explorar Origem] - Concluído
  src/App.css
  src/App.js
  src/Redux/reducers/recipeList.js
  src/components/FilterRecipe.js
  src/components/Header.js
  src/components/RecipeDetail.js
  src/components/RecipeList.js
  src/components/SearchFood.js
  src/index.css
  src/pages/Drinks/ExploreDrink.js
  src/pages/Drinks/ExploreIngredientsDrink.js
  src/pages/Drinks/MainDrinks.js
  src/pages/Drinks/RecipeDetailDrink.js
  src/pages/Foods/ExploreCountry.js
  src/pages/Foods/ExploreFood.js
  src/pages/Foods/ExploreIngredientsFood.js
  src/pages/Foods/MainFood.js
  src/pages/Foods/RecipeDetailFood.js
  src/pages/Login.js
  src/pages/NotFound.js
  src/pages/Profile.js
  src/services/recipeAPI.js
Labels: code-review

#665 [GRUPO 28] [Receita em progresso e Refatoração do botão compartilhar]
  src/App.css
  src/components/ButtonCompartilhar.jsx
  src/components/CardsDeReceitas.jsx
  src/components/ListaCategoriasReceitas.jsx
  src/components/ReceitaEmProgresso/BotaoFavorito.jsx
  src/components/ReceitaEmProgresso/Ingredientes.jsx
  src/helpers/Date.js
  src/helpers/formatIngredientsMeasures.js
  src/images/fundoLogin.jpg
  src/images/logo.png
  src/pages/DetailsReceita.jsx
  src/pages/Login.jsx
  src/pages/Perfil.jsx
  src/pages/ReceitaEmProgresso.jsx
  src/pages/ReceitasFeitas.jsx
  src/pages/detailsElements/CarouselElement.jsx
  src/pages/detailsElements/Titulo.jsx
  src/services/localStorage.js
Labels: code-review

#646 group 31 requisitos 67 ao 69
  src/components/BeveragesInProgressInfo.jsx
  src/components/FoodInProgressInfo.jsx
  src/pages/BeverageRecipe.js
  src/pages/BeveragesInProgress.js
  src/pages/DoneRecipes.js
  src/pages/Explore.js
  src/pages/FavoriteRecipes.js
  src/pages/FoodInProgress.js
  src/pages/FoodRecipe.js
Labels: code-review

#658 Main group 24 req continuar receita
  cypress/integration/recipe_detail_spec.js
  src/App.css
  src/Pages/Bebidas.jsx
  src/Pages/Comidas.jsx
  src/Pages/Detalhes.jsx
  src/Pages/Login.jsx
  src/Pages/ReceitaEmProcesso.jsx
  src/Pages/ReceitasFeitas.jsx
  src/components/DescriptionRecipeCard.jsx
  src/components/Details/FavoriteButton.jsx
  src/components/Details/IngredientsStep.jsx
  src/components/Details/Title.jsx
  src/components/Recommendation.jsx
  src/context/Provider.js
  src/helpers/localStorageAction.jsx
  src/hooks/useLocalStorage.js
Labels: code-review

#669 Main Group 7 req 32
  src/components/Icons.js
  src/pages/DrinkDetails.js
  src/pages/FoodDetails.js
Labels: bug

#671 [Grupo 10] Tela de Explorar
  src/App.js
  src/components/ExploreDrinks.jsx
  src/components/ExploreFoods.jsx
  src/components/ExplorePage.jsx
Labels: code-review

#689 [Group 28]ReceitasFavorias
  src/components/ReceitaEmProgresso/BotaoFavorito.jsx
  src/pages/Perfil.jsx
  src/pages/ReceitaEmProgresso.jsx
  src/pages/ReceitasFavoritas.jsx
  src/pages/ReceitasFeitas.jsx
Labels: code-review

#697 [Group 5] ADD Favorite Recipes Page
  src/Style/FavoriteRecipes.css
  src/pages/FavoriteRecipes.jsx
  src/pages/Perfil.jsx
Labels: code-review

#625 [Group 19] [RECEITAS FAVORITAS]
  package-lock.json
  src/common/components/CategoryButton.jsx
  src/common/components/DoneRecipeCard.jsx
  src/common/components/FavoriteRecipeCard.jsx
  src/common/components/LikeButton.jsx
  src/common/components/ShareButton.jsx
  src/common/pages/DoneRecipes.jsx
  src/common/pages/FavoriteRecipes.jsx
  src/common/pages/Profile.jsx
  src/functions/index.js
Labels: development

#676 [Main group 27] [Explorar por área]
  src/Service/drinkApi.js
  src/Service/foodApi.js
  src/components/AreaExplorer.jsx
  src/components/CardDrink.jsx
  src/components/CardIngredient.jsx
  src/components/CardMeal.jsx
  src/pages/AreaExplorer.jsx
  src/pages/Explore.jsx
  src/pages/MainPage.jsx
  src/pages/NotFound.jsx
  src/pages/SearchIngredients.jsx
Labels: code-review

#469 [Main Group 27] [Explore Ingredients]
  src/Service/drinkApi.js
  src/Service/foodApi.js
  src/components/CardIngredient.jsx
  src/pages/Explore.jsx
  src/pages/MainPage.jsx
  src/pages/SearchIngredients.jsx
Labels: development

#737 [GRUPO 16] req 75 e 76
  src/App.css
  src/components/CardIng.jsx
  src/images/loki-drink.jpg
  src/images/loki-president.jpg
  src/images/loki.png
  src/images/lokirecipes.png
  src/login.css
  src/pages/Explorar.jsx
  src/pages/Login.jsx
  src/pages/Perfil.jsx
  src/pages/SearchDrinksIngredients.jsx
  src/pages/SearchFoodsIngredients.jsx
Labels: code-review

#723 [Grupo 10] Requisito 74
  src/App.js
  src/components/ExpSurprise.jsx
  src/components/ExploreDrinks.jsx
  src/components/ExploreFoods.jsx
  src/context/ProviderRecipes.js
Labels: code-review

#738 [group 5] fix req 18
  src/components/Search.jsx
  src/pages/Perfil.jsx
Labels: code-review

#708 [Grupo 15] Requisitos 75 a 77
  cypress/integration/explore_by_ingredient_spec.js
  src/Hooks/fetchDrinkIngredients.js
  src/Hooks/fetchFoodIngredients.js
  src/Hooks/fetchInicialDrinks.js
  src/Hooks/fetchInicialFiters.js
  src/Hooks/fetchInicialFoods.js
  src/components/FilterBar.js
  src/context/RecipesProvider.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/IngredientesBebidas.js
  src/pages/IngredientesComidas.js
Labels: development

#740 Fix - Requirement 48 - [DONE]
  src/pages/Recipes/RecipesProgress.js
Labels: code-review

#674 G9 CSSs
  src/components/CardsCarousel.js
  src/components/CategoryOptions.js
  src/components/DetailsButton.js
  src/pages/ReceitaEmProgresso.js
  src/services/RecipeDetailsFetch.js
  src/services/SaveInProgress.js
  src/services/SaveToFavorites.js
  src/services/SaveWithFavorites.js
  src/styles/CategoryButtons.css
  src/styles/card.css
  src/styles/header.css
Labels: code-review

#748 Main group 9 adicional tela favorites
  src/pages/ReceitaDetalhes.js
  src/pages/ReceitaEmProgresso.js
  src/pages/RecipesFavorite.jsx
Labels: code-review

#749 Revert "Main group 9 adicional tela favorites"
  src/pages/ReceitaDetalhes.js
  src/pages/ReceitaEmProgresso.js
  src/pages/RecipesFavorite.jsx
Labels: code-review

#753 [Main-Group-6][Req-52]
  src/pages/Recipes/RecipesProgress.js
Labels: code-review

#761 [Grupo 15] Requisito 81: Route NOT FOUND fix
  src/App.js
Labels: code-review

#721 Grupo 25 - Tela principal de receitas
  src/components/SearchBar.jsx
  src/pages/Drink.jsx
  src/pages/Food.jsx
Labels: code-review

#766 [GRUPO 19] AJUSTE GIT
  src/common/pages/Login.jsx
Labels: code-review

#742 [Grupo 10] Requisitos 81 ao 87
  src/App.js
  src/components/DoneRecipes.jsx
  src/components/FavRecipes.jsx
  src/components/Header.jsx
  src/components/NotFoundPage.jsx
  src/components/Profile.jsx
Labels: code-review

#756 [GRUPO 28] [Botão iniciar receita]
  src/pages/DetailsReceita.jsx
  src/services/localStorage.js
Labels: code-review

#755 Feat: requirements 78, 79, 80, 81 [DONE]
  src/App.js
  src/pages/Explore/ExploreArea.js
  src/pages/NotFound/NotFound.js
  src/styles/ExploreArea.css
Labels: code-review

#779 Main-group-23 receitas favoritas
  src/components/ButtonFavorite/ButtonFavorite.js
  src/components/ButtonShare/ButtonShare.js
  src/pages/Detalhes/DetalhesBebidas.js
  src/pages/Detalhes/DetalhesComidas.js
  src/pages/RecipesFavorites/RecipesFavorites.css
  src/pages/RecipesFavorites/RecipesFavorites.js
  src/pages/RecipesMade/RecipesMade.js
Labels: code-review

#782 [Group 1] [Tela Receitas Feitas] - Incompleto
  src/components/RecipeList.js
  src/pages/FavoriteRecipes.js
  src/pages/RecipeDone.js
Labels: code-review

#672 [Group 20] Style Main Page
  package-lock.json
  src/styles/Card.css
  src/styles/Footer.css
Labels: code-review

#771 G9 Correções e CSSs
  src/components/MealsByIngredients.js
  src/pages/Explorar.js
  src/pages/Perfil.js
  src/pages/RecipesFavorite.jsx
  src/styles/header.css
Labels: code-review

#778 [main-group-10] [req 78 a 81]
  src/App.js
  src/components/ExpArea.jsx
  src/components/ExpAreaFood.jsx
  src/components/FoodPage.jsx
  src/components/Footer.jsx
  src/components/SBElements.jsx
  src/context/ProviderRecipes.js
Labels: code-review

#806 Main group 28 refat video
  src/pages/DetailsReceita.jsx
  src/pages/Receitas.jsx
Labels: code-review

#813 [GRUPO 19] Restore Profile Page
  src/common/pages/Profile.jsx
  src/images/profile.jpg
Labels: code-review

#789 [Group 19] - resolve conflitos
  README.md
  package-lock.json
  src/App.js
  src/common/components/CardDrinksIgredients.jsx
  src/common/components/CardMealsArea.jsx
  src/common/components/CardMealsIgredients.jsx
  src/common/pages/DrinksIngrediant.jsx
  src/common/pages/ExploreDrinks.jsx
  src/common/pages/ExploreMeals.jsx
  src/common/pages/Explorer.jsx
  src/common/pages/MealsIngredient.jsx
  src/common/pages/MealsOrigem.jsx
  src/common/pages/NotFound.jsx
  src/services/index.js
Labels: code-review

#815 resolve conflito da 28 com a 16
  src/pages/DetailsReceita.jsx
  src/pages/Receitas.jsx
Labels: code-review

#820 [Main-Group-6][Refactoring]
  src/context/Provider.jsx
  src/pages/Recipes/RecipesDetails.js
  src/pages/Recipes/RecipesProgress.js
Labels: code-review

#824 main-group-23 explorarLocalOrigem
  src/App.js
  src/components/Header/Header.js
  src/components/SearchBar/SearchBar.js
  src/helpers/requests.js
  src/pages/ExploreFoodOrigin/ExploreFoodOrigin.js
  src/pages/Food/Food.js
  src/pages/Page404/Page404.js
  src/pages/Profile/Profile.js
  src/pages/RecipesFavorites/RecipesFavorites.css
  src/pages/RecipesMade/RecipesMade.css
Labels: code-review

#709 Main group 8 favoritos
  src/Pages/ExpoFoodArea.jsx
  src/Pages/FavoriteRecipes.jsx
  src/styles/FavoriteRecipes.css
Labels: code-review

#843 [Main-Group-6][Refactoring-Login]
  src/context/Provider.jsx
  src/pages/User/Login.js
Labels: enhancement

#787 [Group-31] CSS da Tela principal e componentes
  src/App.css
  src/components/BeveragesInProgressInfo.jsx
  src/components/FoodInProgressInfo.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Recommendations.jsx
  src/components/SearchBar.jsx
  src/pages/BeverageIngredients.js
  src/pages/BeverageRecipe.js
  src/pages/Beverages.js
  src/pages/DoneRecipes.js
  src/pages/Explore.js
  src/pages/ExploreBeverages.js
  src/pages/ExploreFood.js
  src/pages/FavoriteRecipes.js
  src/pages/Food.js
  src/pages/FoodByOrigin.js
  src/pages/FoodIngredients.js
  src/pages/FoodRecipe.js
  src/pages/Profile.js
Labels: code-review

#861 [GRUPO 19] [BRANCH DE ESTILIZAÇÃO]
  package-lock.json
  package.json
  src/common/components/CardDrinksIgredients.jsx
  src/common/components/CardMealsArea.jsx
  src/common/components/CardMealsIgredients.jsx
  src/common/components/CategoryButton.jsx
  src/common/components/DoneRecipeCard.jsx
  src/common/components/FavoriteRecipeCard.jsx
  src/common/components/Footer.jsx
  src/common/components/Footer/footer.css
  src/common/components/Header.jsx
  src/common/components/Header/Header.jsx
  src/common/components/Header/header.css
  src/common/components/LikeButton.jsx
  src/common/components/Loading.jsx
  src/common/components/RecipeCard.jsx
  src/common/components/RecommendedRecipes.jsx
  src/common/components/RenderButtonHome.jsx
  src/common/components/RenderButtons.jsx
  src/common/components/RenderDetails.jsx
  src/common/components/SearchBar.jsx
  src/common/components/ShareButton.jsx
  src/common/pages/DoneRecipes.jsx
  src/common/pages/DrinksIngrediant.jsx
  src/common/pages/ExploreDrinks.jsx
  src/common/pages/ExploreMeals.jsx
  src/common/pages/Explorer.jsx
  src/common/pages/FavoriteRecipes.jsx
  src/common/pages/Login.jsx
  src/common/pages/MealsIngredient.jsx
  src/common/pages/MealsOrigem.jsx
  src/common/pages/Profile.jsx
  src/common/pages/RecipeDetails.jsx
  src/common/pages/RecipeInProgress.jsx
  src/common/pages/Recipes.jsx
  src/context/reducers/recipes.js
  src/context/store.js
  src/done.json
  src/fonts/CaslonGraphique-Opti.otf
  src/functions/index.js
  src/images/FINE-CHEFS.png
  src/images/FINE-CHEFS.svg
  src/images/blackHeartIcon.svg
  src/images/drinkIcon.svg
  src/images/exploreIcon.svg
  src/images/fine-chefs-logo.png
  src/images/fine-chefs-logo.svg
  src/images/img-login.svg
  src/images/mealIcon.svg
  src/images/profileIcon.svg
  src/images/searchIcon.svg
  src/images/shareIcon.svg
  src/images/whiteHeartIcon.svg
  src/index.css
  src/loading.json
Labels: code-review

#595 Main group 8 details page - v2
  cypress/integration/footer_spec.js
  src/Components/Details.jsx
  src/Components/DetailsProgress.jsx
  src/Pages/DrinkDetails.jsx
  src/Pages/Explore.jsx
  src/Pages/ExploreDrinks.jsx
  src/Pages/ExploreFoods.jsx
  src/Pages/ExpoDrinksIng.jsx
  src/Pages/ExpoFoodsIng.jsx
  src/Pages/FavoriteRecipes.jsx
  src/Pages/FoodDetailsR.jsx
  src/Pages/Foods.jsx
  src/Pages/Profile.jsx
  src/Pages/Progress.jsx
  src/Pages/RecipesMade.jsx
  src/Pages/Teste.jsx
  src/redux/actions/index.js
  src/redux/reducers/done.js
  src/redux/reducers/index.js
  src/services/services.js
  src/styles/Card.css
  src/styles/Done.css
Labels: code-review

#872 [Grupo 10] Correção do requisito 32
  src/components/AllTagsFromDetailsDrinks.jsx
  src/components/DetailsDrinkPage.jsx
  src/components/DetailsFoodPage.jsx
  src/components/RecommendedDrinks.jsx
  src/components/RecommendedFood.jsx
  src/context/ProviderRecipes.js
Labels: code-review
